name: Deploy to Hostinger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy website to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          protocol: ftps
          port: ${{ secrets.HOSTINGER_PORT }}
          local-dir: ./
          server-dir: ${{ secrets.HOSTINGER_REMOTE_DIR }}

          exclude: |
            **/.git*
            **/.github/**
            **/README.md
